// <auto-generated />
namespace WrightsAtHome.Server.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TriggerWait : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TriggerWait));
        
        string IMigrationMetadata.Id
        {
            get { return "201506141339516_TriggerWait"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
